# Generated by Django 4.2.4 on 2023-09-03 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopdemo', '0002_remove_book_author_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this video', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this commodity', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=255)),
                ('month_sell', models.IntegerField()),
                ('seller', models.CharField(max_length=200)),
                ('rec_from_followed', models.IntegerField()),
                ('video', models.ManyToManyField(help_text='Select a genre for this book', to='shopdemo.video')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
