# Generated by Django 4.2.4 on 2023-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdemo', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='rec_from_friend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
