# Generated by Django 4.2.4 on 2023-09-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdemo', '0006_remove_commodity_detail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='photo',
        ),
        migrations.AlterField(
            model_name='commodity',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
